DEFAULT_EXHIBITS = [
    {
        "id": "star-map-001",
        "title_ru": "Звёздная карта Новгорода",
        "title_en": "Novgorod Star Map",
        "subtitle_ru": "Медная пластина с небесными координатами, XII век",
        "subtitle_en": "A copper sky plate with celestial coordinates, 12th century",
        "description_ru": "Экспонат показывает, как средневековые мастера представляли движение звёзд. NFC-метка у витрины открывает аудиогид и маршрут.",
        "description_en": "The artifact shows how medieval makers imagined the motion of the stars. The NFC tag near the showcase opens the guide and route.",
        "zone": "Зал Космоса",
        "floor": 2,
        "century": "XII век",
        "category": "Астрономия",
        "route_order": 1,
        "image_uri": "http://localhost:8000/uploads/test1.jpg",
        "tags": ["звёзды", "навигация", "медь"],
        "facts": ["На пластине 47 точек-звёзд", "Маршрут начинается с этого объекта"],
        "nfc_code": "star-map-001",
        "is_custom": False,
    },
    {
        "id": "mask-echo-014",
        "title_ru": "Маска Эха",
        "title_en": "The Echo Mask",
        "subtitle_ru": "Ритуальная маска с акустическими резонаторами",
        "subtitle_en": "A ritual mask with acoustic resonators",
        "description_ru": "Внутри маски спрятаны полости, усиливающие голос. В гиде есть режим аудио-реконструкции.",
        "description_en": "Hidden cavities inside the mask amplify the voice. The guide includes an audio reconstruction mode.",
        "zone": "Зал Ритуалов",
        "floor": 1,
        "century": "IX век",
        "category": "Антропология",
        "route_order": 2,
        "image_uri": "http://localhost:8000/uploads/tet.jpg",
        "tags": ["ритуал", "звук", "маска"],
        "facts": ["Резонаторы меняют тембр голоса", "Экспонат лучше слушать в наушниках"],
        "nfc_code": "mask-echo-014",
        "is_custom": False,
    },
]
